- name: printed varibles from playlevel
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks:
  - name: printed varibles from play level
    ansible.builtin.debug:
     msg: " i am learning course is {{COURSE}} trainer is {{TRAINER}} and it will take duration is {{DURATION}}"