- name: printed varibles from prompt level
  hosts: mongodb
  vars_prompt:
  - name: username
    prompt: please enter username
    private: false
  - name: password
    prompt: please enter password
    private: true
  tasks:
  - name: printed varibles from prompt level
    ansible.builtin.debug:
     msg: "username{{USERNAME}} password{{PASSWORD}}"