- name: printed varibles from tasks level
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
   tasks:
   - name: printed varibles from tasks level
     ansible.builtin.debug:
      msg: "i am learning course is {{COURSE}} and trainer is {{TRAINER}} and duration is {{DURATION}}"
   vars:
    HOUSE: own
   - name: printed varibles from tasks level
     ansible.builtin.debug:
      msg: "i am learning course is {{COURSE}} and trainer is {{TRAINER}} and duration is {{DURATION}} i have a {{HOUSE}}"
      